# Generated by Django 5.0.3 on 2026-03-31 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(verbose_name='Дата приёма')),
                ('complaints', models.TextField(verbose_name='Жалобы')),
                ('diagnosis', models.TextField(verbose_name='Диагноз')),
                ('prescription', models.TextField(blank=True, null=True, verbose_name='Назначения')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='Рекомендации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='appointments.visit')),
            ],
            options={
                'verbose_name': 'Запись в медкарте',
                'verbose_name_plural': 'Медицинские карты',
                'ordering': ['-visit_date'],
            },
        ),
    ]
