# Generated by Django 5.0.3 on 2026-03-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='slot_duration',
            field=models.IntegerField(default=20, verbose_name='Длительность приёма (мин)'),
        ),
    ]
