# Generated by Django 5.0.3 on 2026-04-07 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctorprofile_slot_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='category',
        ),
    ]
