# Generated by Django 5.0.3 on 2026-03-31 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='patronymic',
            new_name='middle_name',
        ),
    ]
